# Build environment
version: "3.3"
services:
  builder:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        JAVA_VERSION: 11
        GRADLE_VERSION: 7.1
    environment:
      FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT: 1
      DB_URL: jdbc:postgresql://postgresql:5432/prime_data_hub
    volumes: # Attach the pwd into the image
      - type: bind
        source: ./
        target: /src
    working_dir: /src
    # entrypoint:
    #   - gradle
    #   - "-PDB_URL=jdbc:postgresql://postgresql:5432/prime_data_hub"
    #   - package
    dns:
      - 1.1.1.1
    networks:
      - prime-router_build

  # NOTE: this replaces the docker-infrastructure yaml file
  # There is also no adminer or any other Admin UI that is part of this
  # build docker-compose as we do not want to dictate that.
  # You can connect using psql, or pgAdmin, or ... just point at localhost:5432
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "prime_data_hub"
      POSTGRES_PASSWORD: "changeIT!"
      POSTGRES_USER: "prime"
    ports:
      - 5432:5432
    volumes:
      - vol_postgresql_data:/var/lib/postgresql/data
    networks:
      - prime-router_build

networks:
  prime-router_build:

volumes:
  vol_postgresql_data:
