# This docker compose is intended to setup developer infrastructure
version: "3.3"
services:
  # local PostgreSQL instance with config and persistent volume
  db_pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "changeIT!"
      POSTGRES_USER: "prime"
      POSTGRES_DB: "prime_data_hub"

    ports:
      - "5432:5432"
    volumes:
      - vol_prime_db:/var/lib/postgresql/data

  # local web-based SQL tool for looking in db_pgsql
  db_adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  # For storing a local postegres database
  vol_prime_db:

