# Build environment
version: "3.3"
services:
  builder:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT: 1
      # 172.17.0.1 is the docker bridge gateway
      DB_URL: jdbc:postgresql://172.17.0.1:5432/prime_data_hub
      POSTGRES_URL: jdbc:postgresql://172.17.0.1:5432/prime_data_hub
    volumes:
      - type: bind
        source: ./
        target: /src
    working_dir: /src
    networks:
      - prime-router_build

  # NOTE: this replaces the docker-infrastructure yaml file
  # There is also no adminer or any other Admin UI that is part of this
  # build docker-compose as we do not want to dictate that.
  # You can connect using psql, or pgAdmin, or ... just point at 5432 on your local host
  postgresql:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: "prime_data_hub"
      POSTGRES_PASSWORD: "changeIT!"
      POSTGRES_USER: "prime"
    ports:
      - 5432:5432
    volumes:
      - vol_postgresql_data:/var/lib/postgresql/data
    networks:
      - prime-router_build

networks:
  prime-router_build:

volumes:
  vol_postgresql_data:
