title = "PRIME ReportStream Gitleaks Configuration"

[[rules]]
	description = "Github"
	regex = '''(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}['\"]'''
	tags = ["key", "Github"]

[[rules]]
	description = "Slack"
	regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
	tags = ["key", "Slack" ]

[[rules]]
	description = "Slack Webhook"
	regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
	tags = ["key", "slack"]

[[rules]]
	description = "Env Var"
	regex = '''(?i)(apikey|secret|key|api|password|pass|pw|host)=[0-9a-zA-Z-_.{}]{4,120}'''
	tags = ["key", "envvar"]
    [rules.allowlist]
        files = [
            '''(log)$''',
            '''docker-compose\.yml'''
        ]

[[rules]]
	description = "High Entropy"
	regex = '''[0-9a-zA-Z-_!{}/=]{4,120}'''
  	file = '''(?i)(dump.sql|high-entropy-misc.txt)$'''
	tags = ["entropy"]
    [[rules.Entropies]]
        Min = "4.3"
        Max = "7.0"
    [rules.allowlist]
        files = ['''(pem|ppk|env)$''']
        paths = ['''(.*)?ssh''']

# Global allowlist
[allowlist]
	description = "Allowed File and locations"
	files = ['''(.*?)(jpg|gif|doc|pdf|bin|md|log)$''']
    paths = [
        '''node_modules'''
    ]