# This docker compose is intended to setup a developer 
version: "3.6"  # v3.6 for multi-build target builds
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: static_site

    environment:
      ## PRIME_api -- see ./eleventy.config.js and ./mock/main.mjs
      ##   the URL must be resolvable from inside the container
      #- PRIME_api=http://prime_dev:7072/api   
      - PRIME_api=http://api_mock:9000/api

      - OKTA_baseUrl=hhs-prime.okta.com
      - OKTA_clientId=0oa6fm8j4G1xfrthd4h6
      - OKTA_redirect=http://localhost:7071/api/download

    ports:
      - "7071:7071"

  api_mock:
    build:
      context: .
      dockerfile: Dockerfile
      target: api_mock

    ports:
      - "9000:9000"
