version: "3.3"

services:
  dev-01-network:
    container_name: terraform_state_dev_network
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/dev-01-network

  dev-02-config:
    container_name: terraform_state_dev_config
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/dev-02-config

  dev-03-persistent:
    container_name: terraform_state_dev_persistent
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/dev-03-persistent

  dev-04-app:
    container_name: terraform_state_dev_app
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/dev-04-app
    
  test-01-network:
    container_name: terraform_state_test_network
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/test-01-network

  test-02-config:
    container_name: terraform_state_test_config
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/test-02-config

  test-03-persistent:
    container_name: terraform_state_test_persistent
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/test-03-persistent

  test-04-app:
    container_name: terraform_state_test_app
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/test-04-app

  staging-01-network:
    container_name: terraform_state_staging_network
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/staging-01-network

  staging-02-config:
    container_name: terraform_state_staging_config
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/staging-02-config

  staging-03-persistent:
    container_name: terraform_state_staging_persistent
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/staging-03-persistent

  staging-04-app:
    container_name: terraform_state_staging_app
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/staging-04-app

  prod-01-network:
    container_name: terraform_state_prod_network
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/prod-01-network

  prod-02-config:
    container_name: terraform_state_prod_config
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/prod-02-config

  prod-03-persistent:
    container_name: terraform_state_prod_persistent
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/prod-03-persistent

  prod-04-app:
    container_name: terraform_state_prod_app
    build:
      context: .
    volumes:
      # Bind the app directory instead of building into the docker image for re-usability
      - type: bind
        source: ./app
        target: /app
      # Keep Azure config
      - type: volume
        source: azure_config
        target: /root/.azure
    working_dir: /app/src/environments/prod-04-app

volumes:
  azure_config:
