---
imgPath: /assets/img/
pdfPath: /assets/pdf/
documentationPath: /documentation/

orgs:
  CDC:
    name: Centers for Disease Control and Prevention
    url: https://cdc.gov
  PRIME:
    name: Pandemic Ready Interoperability Modernization Effort
    email: support@prime.cdc.gov
  RS:
    name: ReportStream
    url: https://prime.cdc.gov
    email: support@prime.cdc.gov
  SR:
    name: SimpleReport
    url: https://simplereport.gov
    email: support@prime.cdc.gov
  USDS:
    name: U.S. Digital Service
    url: https://usds.gov
    email: USDS@omb.eop.gov

forms:
  intake:
    name: ELR intake form
    url: https://prime.powerappsportals.us/siw/
