name: td-test

on:
  push:
    branches:
      - td/1256-build-app-in-docker-container

jobs:
  build_in_docker:
    name: build_in_docker
    # needs: pre_job
    if: ${{ github.ref == 'refs/heads/td/1256-build-app-in-docker-container' }}
    # if: ${{ needs.pre_job.outputs.has_router_change == 'true' && needs.pre_job.outputs.is_fork != 'true' }}
    runs-on: ubuntu-latest
    env:
      # These are for CI and not credentials of any system
      POSTGRES_USER: prime
      POSTGRES_PASSWORD: changeIT!
    defaults:
      run:
        working-directory: prime-router

    steps:
      - name: "Check out changes"
        uses: actions/checkout@v2

      # Appears not to be needed on GitHub (but needed when running act locally)
      # - name: Install docker-compose
      #   run: apt-get update && apt-get --yes install docker-compose

      - name: Build Prime Router Package through Docker
        run: bash ./build.sh -- gradle clean package -x fatjar -DDB_USER=$POSTGRES_USER -DDB_PASSWORD=$POSTGRES_PASSWORD

      - name: Show build content after build
        run: ls -hal ./ ./build/