name: td-test

on:
  push:
    branches:
      - td/1256-build-app-in-docker-container

jobs:
  do_build:
    name: Ignore
    # needs: pre_job
    if: ${{ github.ref == 'refs/heads/td/1256-build-app-in-docker-container' }}
    # if: ${{ needs.pre_job.outputs.has_router_change == 'true' && needs.pre_job.outputs.is_fork != 'true' }}
    runs-on: ubuntu-latest
    env:
      # These are for CI and not credentials of any system
      POSTGRES_USER: prime
      POSTGRES_PASSWORD: changeIT!
    defaults:
      run:
        working-directory: prime-router

    steps:
      - name: "Check out changes"
        uses: actions/checkout@v2

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        with:
          postgresql version: 11
          postgresql db: prime_data_hub
          postgresql user: ${{ env.POSTGRES_USER }}
          postgresql password: ${{ env.POSTGRES_PASSWORD }}

      - name: Build Prime Router Package through Docker
        run: bash ./build.sh --refresh-builder --clean -- gradle clean package -x fatjar -DDB_USER=$POSTGRES_USER -DDB_PASSWORD=$POSTGRES_PASSWORD

      - name: Show build content after build
        run: ls -hal ./build/