name: td-test

on:
  push:
    branches:
      - td/1256-build-app-in-docker-container

jobs:
  # pre_job:
  #   name: Pre Job
  #   runs-on: ubuntu-latest
  #   outputs:
  #     has_router_change: ${{ steps.skip_check.outputs.router }}
  #     is_fork: ${{ steps.fork_check.outputs.is_fork }}
  #   steps:
  #     - uses: dorny/paths-filter@v2
  #       id: skip_check
  #       with:
  #         list-files: csv
  #         filters: |
  #           router:
  #             - 'prime-router/**'
  #             - '.github/workflows/build_hub.yml'
  #     - id: fork_check
  #       run: echo "::set-output name=is_fork::${{ github.event.pull_request.head.repo.full_name != github.repository }}"

  do_build:
    name: Ignore
    # needs: pre_job
    if: ${{ github.ref == 'refs/heads/td/1256-build-app-in-docker-container' }}
    # if: ${{ needs.pre_job.outputs.has_router_change == 'true' && needs.pre_job.outputs.is_fork != 'true' }}
    runs-on: ubuntu-latest
    env:
      # These are for CI and not credentials of any system
      POSTGRES_USER: prime
      POSTGRES_PASSWORD: changeIT!
    defaults:
      run:
        working-directory: prime-router

    steps:
      - name: "Check out changes"
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: echo "Hello world from $(pwd) on ref \'${GITHUB_REF}\'"