name: Frontend

on:
  pull_request:
    branches: [ master, production ]

jobs:
  pre_job:
    name: Pre Job
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      is_fork: ${{ steps.fork_check.outputs.is_fork }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["frontend/**"]'
      - id: fork_check
        run: echo "::set-output name=is_fork::${{ github.event.pull_request.head.repo.full_name != github.repository }}"

  build_frontend:
    name: Build Frontend
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' && needs.pre_job.outputs.is_fork != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2

      - name: Run Build Script
        run: bash ci_build.bash

      - name: Save Static Website
        uses: actions/upload-artifact@v2
        with:
          name: static_website
          path: frontend/dist

      - name: Validate static website server
        run: bash ci_validate.bash