name: Frontend

on:
  pull_request:
    branches:
      - master
      - production

jobs:
  pre_job:
    name: Pre Job
    runs-on: ubuntu-latest
    outputs:
      has_frontend_change: ${{ steps.skip_check.outputs.frontend }}
      is_fork: ${{ steps.fork_check.outputs.is_fork }}
    steps:
      - uses: dorny/paths-filter@v2
        id: skip_check
        with:
          list-files: csv
          filters: |
            frontend:
              - 'frontend-react/**'
              - '.github/workflows/build_frontend.yml'
      - id: fork_check
        run: echo "::set-output name=is_fork::${{ github.event.pull_request.head.repo.full_name != github.repository }}"

  build_frontend:
    name: Build Frontend
    needs: pre_job
    if: ${{ needs.pre_job.outputs.has_frontend_change == 'true' && needs.pre_job.outputs.is_fork != 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build React Site
        run: npm run build --if-present

      - name: Save Static Website
        uses: actions/upload-artifact@v2
        with:
          name: static_website
          path: frontend-react/build