openapi: 3.0.1
info:
  title: 'My API'
  version: 1.0.0
paths:
  '/api/me':
    get:
      operationId: me
      responses:
        '200':
          description: Token data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
components:
  schemas:
    TokenData:
      type: object
      properties:
        name:
          type: string
          example: Jane Doe
        email:
          type: string
          format: email
          example: john@example.com
        iat:
          type: integer
          example: 1516239022

  securitySchemes:
    jwt_bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    jwt_cookie_auth:
      type: JWT
      in: cookie
      name: jwt

security:
  - jwt_cookie_auth: []
  - jwt_bearer_auth: []

