openapi: 3.0.1
info:
  title: Prime Data Hub Mock
  version: 0.0.0-mock

paths:
  '/api/me':
    get:
      operationId: me
      responses:
        '200':
          description: Token data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
        '401':
          description: Unauthorized

  '/api/csv-download':
    get:
      operationId: csv-download
      responses:
        '200':
          description: Token data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataDownload'
        '401':
          description: Unauthorized

components:
  schemas:
    TokenData:
      type: object
      properties:
        given_name: 
          type: string
          example: 'Jane'
        family_name: 
          type: string
          example: 'Doe'
        email:
          type: string
          format: email
          example: jane@example.com
        phone:
          type: string
          example: "(555) 867-5309"

    DataDownload:
      type: object
      example:
        today:
          - timestamp: "2021-02-11T21:29:46Z"
            expires: "2021-02-18T21:29:46Z"
            total_tests: 98
            description: "Electronic Lab Record"
            uuid: "64d30357-2541-403c-86dd-6e7e5c627920"
            url: "/api/download?file=64d30357-2541-403c-86dd-6e7e5c627920"

          - timestamp: "2021-02-11T21:23:11Z"
            expires: "2021-02-18T21:23:11Z"
            total_tests: 25
            description: "Electronic Lab Record"
            uuid: "cf0e7e2e-ef07-49a8-bdab-ed1df9b46060"
            url: "/api/download?file=cf0e7e2e-ef07-49a8-bdab-ed1df9b46060"

          - timestamp: "2021-02-11T20:45:54Z"
            expires: "2021-02-18T20:45:54Z"
            total_tests: 24
            description: "Electronic Lab Record"
            uuid: "3f7fa775-c7fb-4468-bf7f-e5b0f1f1c8f7"
            url: "/api/download?file=3f7fa775-c7fb-4468-bf7f-e5b0f1f1c8f7"

        previous:
          - timestamp: "2021-02-10T13:50:56Z"
            expires: "2021-02-06T13:50:56Z"
            total_tests: 196
            description: "Electronic Lab Record"
            uuid: "7728127e-ffca-4174-9042-37bd69a31620"
            url: "/api/download?file=7728127e-ffca-4174-9042-37bd69a31620"

          - timestamp: "2021-02-08T12:30:03Z"
            expires: "2021-02-06T12:30:03Z"
            total_tests: 143
            description: "Electronic Lab Record"
            uuid: "13ba7aca-7130-46e9-8e22-64a4a1078631"
            url: "/api/download?file=13ba7aca-7130-46e9-8e22-64a4a1078631"

          - timestamp: "2021-02-06T03:50:21Z"
            expires: "2021-02-06T03:50:21Z"
            total_tests: 75
            description: "Electronic Lab Record"
            uuid: "c6d4e585-b010-4fa8-af25-ca3887ddc528"
            url: "/api/download?file=c6d4e585-b010-4fa8-af25-ca3887ddc528"

          - timestamp: "2021-02-05T03:40:47Z"
            expires: "2021-02-06T03:40:47Z"
            total_tests: 25
            description: "Electronic Lab Record"
            uuid: "40c7b827-c4b6-40b0-ba04-38508f8422e9"
            url: "/api/download?file=40c7b827-c4b6-40b0-ba04-38508f8422e9"

  securitySchemes:
    jwt_bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    jwt_cookie_auth:
      type: JWT
      in: cookie
      name: jwt

security:
  - jwt_cookie_auth: []
  - jwt_bearer_auth: []
